version: '3'

services:
  utility:
    env_file: .env
    image: buzzingpixel/utility:1.1.0
    container_name: utility-craft-clean-env
    environment:
      HOSTNAME: utility-craft-clean-env
    volumes:
      - .:/app
      - cache-volume:/cache-volume:delegated
      - composer-home-volume:/composer-home-volume:delegated
      - cpresources-volume:/cpresources-volume:delegated
      - db-volume:/db-volume:delegated
      - vendor-volume:/vendor-volume:delegated
    command: bash -c "chmod +x /app/scripts/devUtilityScript.sh && /app/scripts/devUtilityScript.sh"
    networks:
      common-craft-clean-env-network:
  web:
    env_file: .env
    image: buzzingpixel/nginx:1.0.2
    container_name: nginx-craft-clean-env
    environment:
      HOSTNAME: nginx-craft-clean-env
    ports:
      - "${DOCKER_NGINX_PORT}:${DOCKER_NGINX_PORT_TO_PORT}"
    volumes:
      - ${DOCKER_NGINX_CONF_FILE}:/etc/nginx/conf.d/site.conf:delegated
      - .:/app-www:delegated
      - cache-volume:/app-www/storage:delegated
      - cpresources-volume:/app-www/public/cpresources:delegated
      - vendor-volume:/app-www/vendor:delegated
      - ${SSL_CERT}:/fullchain.pem:delegated
      - ${SSL_KEY}:/privkey.pem:delegated
    networks:
      common-craft-clean-env-network:
        aliases:
          - ${SERVER_NAME_ALIAS}
  php:
    env_file: .env
    image: buzzingpixel/php7.2:1.0.6
    container_name: php-craft-clean-env
    environment:
      HOSTNAME: php-craft-clean-env
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - ./serverConfig/php/fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
      - .:/app:delegated
      - .:/app-www:delegated
      - cache-volume:/app-www/storage:delegated
      - composer-home-volume:/composer-home-volume:delegated
      - cpresources-volume:/app-www/public/cpresources:delegated
      - vendor-volume:/app-www/vendor:delegated
    networks:
      common-craft-clean-env-network:
  db:
    env_file: .env
    image: buzzingpixel/mariadb:2.0.1
    container_name: db-craft-clean-env
    restart: always
    environment:
      HOSTNAME: db-craft-clean-env
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    user: "1000:50"
    volumes:
      - ${DOCKER_RSA_FILE}:/tmp/.ssh/id_rsa:delegated
      - ${DOCKER_RSA_PUB_FILE}:/tmp/.ssh/id_rsa.pub:delegated
      - .:/app:delegated
      - db-volume:/var/lib/mysql:delegated
    ports:
      - "${DOCKER_DB_PORT}:3306"
    networks:
      common-craft-clean-env-network:

volumes:
  cache-volume:
  composer-home-volume:
  cpresources-volume:
  db-volume:
  vendor-volume:

networks:
  common-craft-clean-env-network:
